on: pull_request

name: Continuous Integration

env:
  RUSTFLAGS: -D warnings

jobs:
  ci:
    name: ${{ matrix.target.name }} [${{ matrix.rust-version }}]
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        run-tests: [true]
        rust-version: ["stable", "1.62.1"]
        target:
          - name: Linux
            os: ubuntu-latest
            extra-flags: --all-features

          - name: Linux (no-std)
            os: ubuntu-latest
            extra-flags: --no-default-features

          - name: Windows
            os: windows-latest
            extra-flags: --all-features

          - name: Windows (no-std)
            os: windows-latest
            extra-flags: --no-default-features

          - name: Bare Metal (no-std)
            os: ubuntu-latest
            extra-flags: --no-default-features
            run-tests: false
            env:
              TARGET: thumbv7em-none-eabihf


    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          targets: ${{ matrix.target.env.TARGET || '' }}
          toolchain: ${{ matrix.rust-version }}
          components: clippy, rustfmt

      - run: cargo fmt --check --all
      - run: cargo clippy ${{ matrix.target.extra-flags }}
      - run: cargo build ${{ matrix.target.extra-flags }}

      - if: matrix.run-tests
        run: |
          cargo test ${{ matrix.target.extra-flags }}
          cargo run ${{ matrix.target.extra-flags }} --example 256_colors
          cargo run ${{ matrix.target.extra-flags }} --example hyperlink
          cargo run ${{ matrix.target.extra-flags }} --example title
