on: pull_request

name: Continuous integration

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - run: cargo build
      - run: cargo test
      - run: cargo fmt --check --all
      - run: cargo clippy -- -D warnings
